version: "3.9"
services:
  postgres:
    image: postgres:15.0
    container_name: postgre
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      ALLOW_IP_RANGE=: 0.0.0.0/0
    ports:
      - "5433:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbit
    environment:
      ALLOW_IP_RANGE=: 0.0.0.0/0
    ports:
        - "5672:5672"
        - "15672:15672"
    restart: always