server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver


  mail:
    host:
    username:
    password:
    port:
    protocol:

  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-main.yml

  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    root: INFO
  file:
    name: logger.log
    path: /